apiVersion: v1
kind: Service
metadata:
  name: devops-sample-service
spec:
  type: ClusterIP
  selector:
    app: devops-sample
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
