---
- name: Setup Docker host and deploy docker-compose stack
  hosts: targets
  become: true
  vars:
    project_dir: /opt/devops-sample
  tasks:
    - name: Install apt prerequisites
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install docker & docker-compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure docker service running
      service:
        name: docker
        state: started
        enabled: true

    - name: Create project dir
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Copy project (docker-compose + nginx + docker folder + app)
      synchronize:
        src: "{{ playbook_dir }}/.."
        dest: "{{ project_dir }}"
        rsync_opts:
          - "--exclude=.git"
        recursive: yes

    - name: Start docker-compose stack
      become: true
      community.docker.docker_compose:
        project_src: "{{ project_dir }}"
        state: present
        build: yes
