apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-starter-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: apps.example.com
    http:
      paths:
      - path: /flask
        pathType: Prefix
        backend:
          service:
            name: flask-svc
            port:
              number: 5000
      - path: /node
        pathType: Prefix
        backend:
          service:
            name: node-svc
            port:
              number: 3000
      - path: /spring
        pathType: Prefix
        backend:
          service:
            name: spring-svc
            port:
              number: 8080
      - path: /go
        pathType: Prefix
        backend:
          service:
            name: go-svc
            port:
              number: 8080
      - path: /react
        pathType: Prefix
        backend:
          service:
            name: react-svc
            port:
              number: 80
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: html-svc
            port:
              number: 80
